-- SQL to load countries into the countries table
INSERT INTO countries (id, name, code, iocCode, createdAt, updatedAt) VALUES
('RUS', 'Russia', 'RU', 'RUS', strftime('%s','now'), strftime('%s','now')),
('CAN', 'Canada', 'CA', 'CAN', strftime('%s','now'), strftime('%s','now')),
('NGA', 'Nigeria', 'NG', 'NGR', strftime('%s','now'), strftime('%s','now')),
('NLD', 'Netherlands', 'NL', 'NED', strftime('%s','now'), strftime('%s','now')),
('NOR', 'Norway', 'NO', 'NOR', strftime('%s','now'), strftime('%s','now')),
('KAZ', 'Kazakhstan', 'KZ', 'KAZ', strftime('%s','now'), strftime('%s','now')),
('FRA', 'France', 'FR', 'FRA', strftime('%s','now'), strftime('%s','now')),
('KOR', 'Korea (South)', 'KR', 'KOR', strftime('%s','now'), strftime('%s','now')),
('GBR', 'United Kingdom', 'GB', 'GBR', strftime('%s','now'), strftime('%s','now')),
('YUG', 'Yugoslavia', 'YU', 'YUG', strftime('%s','now'), strftime('%s','now')),
('ITA', 'Italy', 'IT', 'ITA', strftime('%s','now'), strftime('%s','now')),
('PRY', 'Paraguay', 'PY', 'PAR', strftime('%s','now'), strftime('%s','now')),
('SVN', 'Slovenia', 'SI', 'SLO', strftime('%s','now'), strftime('%s','now')),
('VEN', 'Venezuela', 'VE', 'VEN', strftime('%s','now'), strftime('%s','now')),
('LTU', 'Lithuania', 'LT', 'LTU', strftime('%s','now'), strftime('%s','now')),
('LVA', 'Latvia', 'LV', 'LAT', strftime('%s','now'), strftime('%s','now')),
('SVK', 'Slovakia', 'SK', 'SVK', strftime('%s','now'), strftime('%s','now')),
('SRB', 'Serbia', 'RS', 'SRB', strftime('%s','now'), strftime('%s','now')),
('LBN', 'Lebanon', 'LB', 'LIB', strftime('%s','now'), strftime('%s','now')),
('THA', 'Thailand', 'TH', 'THA', strftime('%s','now'), strftime('%s','now')),
('BEL', 'Belgium', 'BE', 'BEL', strftime('%s','now'), strftime('%s','now')),
('JAM', 'Jamaica', 'JM', 'JAM', strftime('%s','now'), strftime('%s','now')),
('ZAF', 'South Africa', 'ZA', 'RSA', strftime('%s','now'), strftime('%s','now')),
('HTI', 'Haiti', 'HT', 'HAI', strftime('%s','now'), strftime('%s','now')),
('EST', 'Estonia', 'EE', 'EST', strftime('%s','now'), strftime('%s','now')),
('DEU', 'Germany', 'DE', 'GER', strftime('%s','now'), strftime('%s','now')),
('CZE', 'Czechia', 'CZ', 'CZE', strftime('%s','now'), strftime('%s','now')),
('ROU', 'Romania', 'RO', 'ROU', strftime('%s','now'), strftime('%s','now')),
('HRV', 'Croatia (Hrvatska)', 'HR', 'CRO', strftime('%s','now'), strftime('%s','now')),
('MEX', 'Mexico', 'MX', 'MEX', strftime('%s','now'), strftime('%s','now')),
('ISR', 'Israel', 'IL', 'ISR', strftime('%s','now'), strftime('%s','now')),
('CHE', 'Switzerland', 'CH', 'SUI', strftime('%s','now'), strftime('%s','now')),
('POL', 'Poland', 'PL', 'POL', strftime('%s','now'), strftime('%s','now')),
('BLR', 'Belarus', 'BY', 'BLR', strftime('%s','now'), strftime('%s','now')),
('HUN', 'Hungary', 'HU', 'HUN', strftime('%s','now'), strftime('%s','now')),
('SWE', 'Sweden', 'SE', 'SWE', strftime('%s','now'), strftime('%s','now')),
('BRA', 'Brazil', 'BR', 'BRA', strftime('%s','now'), strftime('%s','now')),
('CHN', 'China', 'CN', 'CHN', strftime('%s','now'), strftime('%s','now')),
('GRC', 'Greece', 'GR', 'GRE', strftime('%s','now'), strftime('%s','now')),
('UKR', 'Ukraine', 'UA', 'UKR', strftime('%s','now'), strftime('%s','now')),
('JPN', 'Japan', 'JP', 'JPN', strftime('%s','now'), strftime('%s','now')),
('AUS', 'Australia', 'AU', 'AUS', strftime('%s','now'), strftime('%s','now')),
('FIN', 'Finland', 'FI', 'FIN', strftime('%s','now'), strftime('%s','now')),
('IRL', 'Ireland', 'IE', 'IRL', strftime('%s','now'), strftime('%s','now')),
('DNK', 'Denmark', 'DK', 'DEN', strftime('%s','now'), strftime('%s','now')),
('AUT', 'Austria', 'AT', 'AUT', strftime('%s','now'), strftime('%s','now')),
('USA', 'United States', 'US', 'USA', strftime('%s','now'), strftime('%s','now')),
('GUY', 'Guyana', 'GY', 'GUY', strftime('%s','now'), strftime('%s','now')),
('BHS', 'Bahamas', 'BS', 'BAH', strftime('%s','now'), strftime('%s','now'));
